FROM gradle:7.0-jdk11

RUN mkdir /app

WORKDIR /app

COPY . /app

RUN gradle dependencies

RUN gradle build

RUN cp build/libs/demopg-0.0.1-SNAPSHOT.jar /app/demopg-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/app/demopg-0.0.1-SNAPSHOT.jar"]
