# Stage 1

FROM gradle:7.0-jdk11 as builder

RUN mkdir /app

WORKDIR /app

COPY . /app

RUN gradle dependencies

RUN gradle build

# Stage 2

FROM openjdk:11-jre-slim-buster

RUN mkdir /app

COPY --from=builder /app/build/libs/demopg-0.0.1-SNAPSHOT.jar /app/demopg-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/app/demopg-0.0.1-SNAPSHOT.jar"]
